syntax = "proto3";

service CalculadoraService {
    rpc OperacaoEscolhida (OperacaoEscolhidaRequest) returns (OperacaoEscolhidaResponse) {};
}

service SomarService {
    rpc Somar (SomarRequest) returns (SomarResponse) {};
}

service SubtrairService {
    rpc Subtrair (SubtrairRequest) returns (SubtrairResponse) {};
}

service MultiplicarService {
    rpc Multiplicar (MultiplicarRequest) returns (MultiplicarResponse) {};
}

service DividirService {
    rpc Dividir (DividirRequest) returns (DividirResponse) {};
}

message SomarRequest {
    int32 parcela1 = 1;
    int32 parcela2 = 2;
}

message SomarResponse {
    int32 resultado = 1;
}

message SubtrairRequest {
    int32 minuendo = 1;
    int32 subtraendo = 2;
}

message SubtrairResponse {
    int32 resultado = 1;
}

message MultiplicarRequest {
    int32 fator1 = 1;
    int32 fator2 = 2;
}

message MultiplicarResponse {
    int32 resultado = 1;
}

message DividirRequest {
    int32 dividendo = 1;
    int32 divisor = 2;
}

message DividirResponse {
    int32 quociente = 1;
    int32 resto = 2;
}

message OperacaoEscolhidaRequest {
    string operacao = 1;
    int32 entrada1 = 2;
    int32 entrada2 = 3;
}

message OperacaoEscolhidaResponse {
    int32 saida1 = 1;
    int32 saida2 = 2;
    optional string error = 3;
}